# from typing import Union
# from fastapi import FastAPI

# app = FastAPI()


# @app.get("/")
# def read_root(): # 或是用index(): 這也可以
#     return {"Hello": "World"}
# # http://127.0.0.1:8000/
# # http://127.0.0.1:8000
# # 這個是得出"Hello": "World"


# @app.get("/items/{item_id}")
# def read_item(item_id: int, q: Union[str, None] = None):
#     return {"item_id": item_id, "q": q}
# # http://127.0.0.1:8000/items/5?q=some
# # 網址的"5" 可以改成其他數字，"item_id"的值也會相對應修改
# # q=some，這也可以改成其他，"q"也會修改
# # "item_id": 80,
# # "q": "some"



# # uvicorn learn_main:app --reload

list = ['step up their attack',
 'approach',
 'n a landslide victory',
 'cavalier',
 'rabble',
 'accomplished',
 'painful blows against ',
 'hermas',
 'being held in Gaza',
 'caution',
 'sanctions',
 'f several',
 'incidents of violence against Palestinian civilians',
 'the reported sanctions',
 'the height of absurdity and again',
 'impose sanctions on a unit',
 'committing human rights violations',
 'battalion',
 'breached some of those rules',
 'battalion',
 'but that set various hairs running',
 'pretty fierce backlash',
 'not ',
 'gonna',
 ' improve',
 'matters',
 'put out a statement',
 'are really pushing back',
 'hard on this one',
 'so',
 " we're in the finishing stretch",
 'dithering',
 'is not some abstract issue of political machination',
 'have also exploited their vulnerability',
 'but stress the importance of rapid delivery',
 'for many ',
 'Sunday',
 ' means',
 'a service at ',
 'st',
 " Michael's cathedral and under the golden domes",
 'underground',
 'metro will always Trump the wet streets abov',
 'withstand',
 'hypothetical eventualities',
 'contingencies',
 'republicans unfortunately skeptical towards aid for ',
 'for',
 ' Ukraine',
 'political',
 'hurdles',
 "he'll be under pressure to make this American package",
 'count',
 'minced',
 'humiliated',
 'in any case',
 'dismissed',
 'as direct support of terrorist',
 'exacerbate regional',
 'security crises around the world',
 'clips of lawmaker',
 'entrepreneur',
 'many Pro war bloggers have stuck to the familiar narrative',
 'that the us is only doing this to weaken Russia',
 'preparedness',
 'ahead of a new phase of the wa',
 'extend its influence elsewhere',
 'leading more towards',
 'Moscow',
 'depart',
 'elsewhere',
 'growing anti French sentiment',
 'seen as still using their colonial influence in an unfair way',
 'reluctant',
 'investment',
 'it was a big hub for their effort to ',
 'to',
 ' tackle ',
 'islamis',
 ' militants',
 'pivot towards Moscow',
 'intervention',
 'presence',
 'provocation',
 'and it kind of spurs them on ',
 'Wilross',
 'ambush',
 'pursued',
 'Pro',
 'Chinese party',
 'pristine',
 'a geopolitical hotspot',
 'making conditions',
 'worse in the days ahead',
 'beaking',
 'disrupted',
 'come Amid disappointment',
 'elaborately',
 'an opportunity for activism',
 'obstacles',
 'passed its first ',
 'everlaw',
 'on sexual orientation and gender identity',
 'same sex unions in any form',
 'Rico ',
 'nakata',
 " is taking part in today's March",
 'as identical to opposite sex marriages',
 'referendum',
 'mares',
 'boycotted',
 'farce',
 'tiny turnou',
 'municipalities',
 'miniscule',
 'remedy',
 'untenable',
 'casting their ballots over the course of six weeks',
 'wake',
 'tech Hu',
 'drawbacks',
 'expanding',
 'we are all sweltering',
 'suburb',
 "t for the city's flood of incomers",
 'not in an optimum state',
 'is one of those filling the gaps',
 'so',
 " he's had to hike prices",
 'accusations',
 'arrogance',
 'sociopath',
 'remorse',
 'favorably',
 'berets',
 'pressurized',
 'evaporated',
 'and that they act out in an attempt to access some emotion',
 'clicked',
 'memoir',
 'coping mechanisms',
 'that are constructive as opposed to destructive',
 'sports great shared experience',
 'astonishment',
 'repertoire',
 'ranging from contemporary to baroque',
 'extraordinary',
 'tributes',
 'enthusiasm',
 'no bounds a']

print(len(list))
